### ISSUE TITLE
Wrong Control Mapping

### ISSUE THREAD

**Issue by Henrique194** [brosseaualex/DDWolf#18]
Background

Operating System and version: Windows 11

Bug description

Observed behavior:
When customizing the keyboard controls, there is a problem with the labeling of the keys:
"Bkwrd" maps the right movement;
"Frwd" maps the backward movement;
"Left" maps the forward movement;

I tested the same game files under the DOS executable using DOSBox and it does not have this problem.

Expected behavior:
"Bkwrd" should map the backward movement;
"Frwd" should map the forward movement;
"Left" should map  the left movement;

**Comment by brosseaualex** [comment]
Able to reproduce the issue, will be fixed in next release.

**Comment by brosseaualex** [comment]
Fixed in v1.1.1
